//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Camozzi.Model.DataService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Project", Namespace="http://schemas.datacontract.org/2004/07/DataController.DTO_Model")]
    [System.SerializableAttribute()]
    public partial class Project : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowChangesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Camozzi.Model.DataService.User CreatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreatorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DeptIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Camozzi.Model.DataService.Dept DeptsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FinishField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Camozzi.Model.DataService.User ManagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ManagerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Camozzi.Model.DataService.User WorkerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowChanges {
            get {
                return this.AllowChangesField;
            }
            set {
                if ((this.AllowChangesField.Equals(value) != true)) {
                    this.AllowChangesField = value;
                    this.RaisePropertyChanged("AllowChanges");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Camozzi.Model.DataService.User Creator {
            get {
                return this.CreatorField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatorField, value) != true)) {
                    this.CreatorField = value;
                    this.RaisePropertyChanged("Creator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreatorId {
            get {
                return this.CreatorIdField;
            }
            set {
                if ((this.CreatorIdField.Equals(value) != true)) {
                    this.CreatorIdField = value;
                    this.RaisePropertyChanged("CreatorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DeptId {
            get {
                return this.DeptIdField;
            }
            set {
                if ((this.DeptIdField.Equals(value) != true)) {
                    this.DeptIdField = value;
                    this.RaisePropertyChanged("DeptId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Camozzi.Model.DataService.Dept Depts {
            get {
                return this.DeptsField;
            }
            set {
                if ((object.ReferenceEquals(this.DeptsField, value) != true)) {
                    this.DeptsField = value;
                    this.RaisePropertyChanged("Depts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Finish {
            get {
                return this.FinishField;
            }
            set {
                if ((this.FinishField.Equals(value) != true)) {
                    this.FinishField = value;
                    this.RaisePropertyChanged("Finish");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Camozzi.Model.DataService.User Manager {
            get {
                return this.ManagerField;
            }
            set {
                if ((object.ReferenceEquals(this.ManagerField, value) != true)) {
                    this.ManagerField = value;
                    this.RaisePropertyChanged("Manager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ManagerId {
            get {
                return this.ManagerIdField;
            }
            set {
                if ((this.ManagerIdField.Equals(value) != true)) {
                    this.ManagerIdField = value;
                    this.RaisePropertyChanged("ManagerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((this.PriorityField.Equals(value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Start {
            get {
                return this.StartField;
            }
            set {
                if ((this.StartField.Equals(value) != true)) {
                    this.StartField = value;
                    this.RaisePropertyChanged("Start");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Camozzi.Model.DataService.User Worker {
            get {
                return this.WorkerField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkerField, value) != true)) {
                    this.WorkerField = value;
                    this.RaisePropertyChanged("Worker");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/DataController.DTO_Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Camozzi.Model.DataService.Project[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Camozzi.Model.DataService.Project))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Camozzi.Model.DataService.Account))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Camozzi.Model.DataService.Dept))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Camozzi.Model.DataService.Reclamation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Camozzi.Model.DataService.Reclamation[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Camozzi.Model.DataService.User[]))]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Camozzi.Model.DataService.Account AccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object AllProjectsRowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object AllReclamationRowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Camozzi.Model.DataService.Dept DeptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DeptIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object SelfProjectsRowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object SelfReclamationRowField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Camozzi.Model.DataService.Account Account {
            get {
                return this.AccountField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountField, value) != true)) {
                    this.AccountField = value;
                    this.RaisePropertyChanged("Account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object AllProjectsRow {
            get {
                return this.AllProjectsRowField;
            }
            set {
                if ((object.ReferenceEquals(this.AllProjectsRowField, value) != true)) {
                    this.AllProjectsRowField = value;
                    this.RaisePropertyChanged("AllProjectsRow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object AllReclamationRow {
            get {
                return this.AllReclamationRowField;
            }
            set {
                if ((object.ReferenceEquals(this.AllReclamationRowField, value) != true)) {
                    this.AllReclamationRowField = value;
                    this.RaisePropertyChanged("AllReclamationRow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Camozzi.Model.DataService.Dept Dept {
            get {
                return this.DeptField;
            }
            set {
                if ((object.ReferenceEquals(this.DeptField, value) != true)) {
                    this.DeptField = value;
                    this.RaisePropertyChanged("Dept");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DeptId {
            get {
                return this.DeptIdField;
            }
            set {
                if ((this.DeptIdField.Equals(value) != true)) {
                    this.DeptIdField = value;
                    this.RaisePropertyChanged("DeptId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail {
            get {
                return this.MailField;
            }
            set {
                if ((object.ReferenceEquals(this.MailField, value) != true)) {
                    this.MailField = value;
                    this.RaisePropertyChanged("Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object SelfProjectsRow {
            get {
                return this.SelfProjectsRowField;
            }
            set {
                if ((object.ReferenceEquals(this.SelfProjectsRowField, value) != true)) {
                    this.SelfProjectsRowField = value;
                    this.RaisePropertyChanged("SelfProjectsRow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object SelfReclamationRow {
            get {
                return this.SelfReclamationRowField;
            }
            set {
                if ((object.ReferenceEquals(this.SelfReclamationRowField, value) != true)) {
                    this.SelfReclamationRowField = value;
                    this.RaisePropertyChanged("SelfReclamationRow");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dept", Namespace="http://schemas.datacontract.org/2004/07/DataController.DTO_Model")]
    [System.SerializableAttribute()]
    public partial class Dept : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/DataController.DTO_Model")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowCommmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowCreateAllField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowCreateSelfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowReclamationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowRowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowCommment {
            get {
                return this.AllowCommmentField;
            }
            set {
                if ((this.AllowCommmentField.Equals(value) != true)) {
                    this.AllowCommmentField = value;
                    this.RaisePropertyChanged("AllowCommment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowCreateAll {
            get {
                return this.AllowCreateAllField;
            }
            set {
                if ((this.AllowCreateAllField.Equals(value) != true)) {
                    this.AllowCreateAllField = value;
                    this.RaisePropertyChanged("AllowCreateAll");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowCreateSelf {
            get {
                return this.AllowCreateSelfField;
            }
            set {
                if ((this.AllowCreateSelfField.Equals(value) != true)) {
                    this.AllowCreateSelfField = value;
                    this.RaisePropertyChanged("AllowCreateSelf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowReclamation {
            get {
                return this.AllowReclamationField;
            }
            set {
                if ((this.AllowReclamationField.Equals(value) != true)) {
                    this.AllowReclamationField = value;
                    this.RaisePropertyChanged("AllowReclamation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowRow {
            get {
                return this.AllowRowField;
            }
            set {
                if ((this.AllowRowField.Equals(value) != true)) {
                    this.AllowRowField = value;
                    this.RaisePropertyChanged("AllowRow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reclamation", Namespace="http://schemas.datacontract.org/2004/07/DataController.DTO_Model")]
    [System.SerializableAttribute()]
    public partial class Reclamation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowChangesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Camozzi.Model.DataService.User CreatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreatorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FinishField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Camozzi.Model.DataService.User ManagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ManagerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomenclatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReclamationActField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SendField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SolutionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Camozzi.Model.DataService.User WorkerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Act {
            get {
                return this.ActField;
            }
            set {
                if ((object.ReferenceEquals(this.ActField, value) != true)) {
                    this.ActField = value;
                    this.RaisePropertyChanged("Act");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowChanges {
            get {
                return this.AllowChangesField;
            }
            set {
                if ((this.AllowChangesField.Equals(value) != true)) {
                    this.AllowChangesField = value;
                    this.RaisePropertyChanged("AllowChanges");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Client {
            get {
                return this.ClientField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientField, value) != true)) {
                    this.ClientField = value;
                    this.RaisePropertyChanged("Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Camozzi.Model.DataService.User Creator {
            get {
                return this.CreatorField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatorField, value) != true)) {
                    this.CreatorField = value;
                    this.RaisePropertyChanged("Creator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreatorId {
            get {
                return this.CreatorIdField;
            }
            set {
                if ((this.CreatorIdField.Equals(value) != true)) {
                    this.CreatorIdField = value;
                    this.RaisePropertyChanged("CreatorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Finish {
            get {
                return this.FinishField;
            }
            set {
                if ((this.FinishField.Equals(value) != true)) {
                    this.FinishField = value;
                    this.RaisePropertyChanged("Finish");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Camozzi.Model.DataService.User Manager {
            get {
                return this.ManagerField;
            }
            set {
                if ((object.ReferenceEquals(this.ManagerField, value) != true)) {
                    this.ManagerField = value;
                    this.RaisePropertyChanged("Manager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ManagerId {
            get {
                return this.ManagerIdField;
            }
            set {
                if ((this.ManagerIdField.Equals(value) != true)) {
                    this.ManagerIdField = value;
                    this.RaisePropertyChanged("ManagerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nomenclature {
            get {
                return this.NomenclatureField;
            }
            set {
                if ((object.ReferenceEquals(this.NomenclatureField, value) != true)) {
                    this.NomenclatureField = value;
                    this.RaisePropertyChanged("Nomenclature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Production {
            get {
                return this.ProductionField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductionField, value) != true)) {
                    this.ProductionField = value;
                    this.RaisePropertyChanged("Production");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReclamationAct {
            get {
                return this.ReclamationActField;
            }
            set {
                if ((object.ReferenceEquals(this.ReclamationActField, value) != true)) {
                    this.ReclamationActField = value;
                    this.RaisePropertyChanged("ReclamationAct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Send {
            get {
                return this.SendField;
            }
            set {
                if ((this.SendField.Equals(value) != true)) {
                    this.SendField = value;
                    this.RaisePropertyChanged("Send");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Solution {
            get {
                return this.SolutionField;
            }
            set {
                if ((this.SolutionField.Equals(value) != true)) {
                    this.SolutionField = value;
                    this.RaisePropertyChanged("Solution");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Start {
            get {
                return this.StartField;
            }
            set {
                if ((this.StartField.Equals(value) != true)) {
                    this.StartField = value;
                    this.RaisePropertyChanged("Start");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Camozzi.Model.DataService.User Worker {
            get {
                return this.WorkerField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkerField, value) != true)) {
                    this.WorkerField = value;
                    this.RaisePropertyChanged("Worker");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataService.ICService")]
    public interface ICService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/GetProjects", ReplyAction="http://tempuri.org/ICService/GetProjectsResponse")]
        Camozzi.Model.DataService.Project[] GetProjects();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/GetProjects", ReplyAction="http://tempuri.org/ICService/GetProjectsResponse")]
        System.Threading.Tasks.Task<Camozzi.Model.DataService.Project[]> GetProjectsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/AddReclamation", ReplyAction="http://tempuri.org/ICService/AddReclamationResponse")]
        void AddReclamation(Camozzi.Model.DataService.Reclamation t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/AddReclamation", ReplyAction="http://tempuri.org/ICService/AddReclamationResponse")]
        System.Threading.Tasks.Task AddReclamationAsync(Camozzi.Model.DataService.Reclamation t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/DeleteReclamation", ReplyAction="http://tempuri.org/ICService/DeleteReclamationResponse")]
        void DeleteReclamation(Camozzi.Model.DataService.Reclamation t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/DeleteReclamation", ReplyAction="http://tempuri.org/ICService/DeleteReclamationResponse")]
        System.Threading.Tasks.Task DeleteReclamationAsync(Camozzi.Model.DataService.Reclamation t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/UpdateReclamation", ReplyAction="http://tempuri.org/ICService/UpdateReclamationResponse")]
        void UpdateReclamation(Camozzi.Model.DataService.Reclamation t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/UpdateReclamation", ReplyAction="http://tempuri.org/ICService/UpdateReclamationResponse")]
        System.Threading.Tasks.Task UpdateReclamationAsync(Camozzi.Model.DataService.Reclamation t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/GetByDateReclamation", ReplyAction="http://tempuri.org/ICService/GetByDateReclamationResponse")]
        Camozzi.Model.DataService.Reclamation[] GetByDateReclamation(System.DateTime start, System.DateTime finish);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/GetByDateReclamation", ReplyAction="http://tempuri.org/ICService/GetByDateReclamationResponse")]
        System.Threading.Tasks.Task<Camozzi.Model.DataService.Reclamation[]> GetByDateReclamationAsync(System.DateTime start, System.DateTime finish);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/AddUser", ReplyAction="http://tempuri.org/ICService/AddUserResponse")]
        void AddUser(Camozzi.Model.DataService.User t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/AddUser", ReplyAction="http://tempuri.org/ICService/AddUserResponse")]
        System.Threading.Tasks.Task AddUserAsync(Camozzi.Model.DataService.User t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/DeleteUser", ReplyAction="http://tempuri.org/ICService/DeleteUserResponse")]
        void DeleteUser(Camozzi.Model.DataService.User t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/DeleteUser", ReplyAction="http://tempuri.org/ICService/DeleteUserResponse")]
        System.Threading.Tasks.Task DeleteUserAsync(Camozzi.Model.DataService.User t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/UpdateUser", ReplyAction="http://tempuri.org/ICService/UpdateUserResponse")]
        void UpdateUser(Camozzi.Model.DataService.User t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/UpdateUser", ReplyAction="http://tempuri.org/ICService/UpdateUserResponse")]
        System.Threading.Tasks.Task UpdateUserAsync(Camozzi.Model.DataService.User t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/AddProject", ReplyAction="http://tempuri.org/ICService/AddProjectResponse")]
        void AddProject(Camozzi.Model.DataService.Project t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/AddProject", ReplyAction="http://tempuri.org/ICService/AddProjectResponse")]
        System.Threading.Tasks.Task AddProjectAsync(Camozzi.Model.DataService.Project t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/DeleteProject", ReplyAction="http://tempuri.org/ICService/DeleteProjectResponse")]
        void DeleteProject(Camozzi.Model.DataService.Project t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/DeleteProject", ReplyAction="http://tempuri.org/ICService/DeleteProjectResponse")]
        System.Threading.Tasks.Task DeleteProjectAsync(Camozzi.Model.DataService.Project t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/GetUsers", ReplyAction="http://tempuri.org/ICService/GetUsersResponse")]
        Camozzi.Model.DataService.User[] GetUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/GetUsers", ReplyAction="http://tempuri.org/ICService/GetUsersResponse")]
        System.Threading.Tasks.Task<Camozzi.Model.DataService.User[]> GetUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/CheckPassword", ReplyAction="http://tempuri.org/ICService/CheckPasswordResponse")]
        bool CheckPassword(string password, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/CheckPassword", ReplyAction="http://tempuri.org/ICService/CheckPasswordResponse")]
        System.Threading.Tasks.Task<bool> CheckPasswordAsync(string password, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/GetReclamations", ReplyAction="http://tempuri.org/ICService/GetReclamationsResponse")]
        Camozzi.Model.DataService.Reclamation[] GetReclamations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/GetReclamations", ReplyAction="http://tempuri.org/ICService/GetReclamationsResponse")]
        System.Threading.Tasks.Task<Camozzi.Model.DataService.Reclamation[]> GetReclamationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/GetByDateAndDeptProject", ReplyAction="http://tempuri.org/ICService/GetByDateAndDeptProjectResponse")]
        Camozzi.Model.DataService.Project[] GetByDateAndDeptProject(System.DateTime start, System.DateTime finish, int deptid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/GetByDateAndDeptProject", ReplyAction="http://tempuri.org/ICService/GetByDateAndDeptProjectResponse")]
        System.Threading.Tasks.Task<Camozzi.Model.DataService.Project[]> GetByDateAndDeptProjectAsync(System.DateTime start, System.DateTime finish, int deptid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/UpdateProject", ReplyAction="http://tempuri.org/ICService/UpdateProjectResponse")]
        void UpdateProject(Camozzi.Model.DataService.Project t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICService/UpdateProject", ReplyAction="http://tempuri.org/ICService/UpdateProjectResponse")]
        System.Threading.Tasks.Task UpdateProjectAsync(Camozzi.Model.DataService.Project t);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICServiceChannel : Camozzi.Model.DataService.ICService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CServiceClient : System.ServiceModel.ClientBase<Camozzi.Model.DataService.ICService>, Camozzi.Model.DataService.ICService {
        
        public CServiceClient() {
        }
        
        public CServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Camozzi.Model.DataService.Project[] GetProjects() {
            return base.Channel.GetProjects();
        }
        
        public System.Threading.Tasks.Task<Camozzi.Model.DataService.Project[]> GetProjectsAsync() {
            return base.Channel.GetProjectsAsync();
        }
        
        public void AddReclamation(Camozzi.Model.DataService.Reclamation t) {
            base.Channel.AddReclamation(t);
        }
        
        public System.Threading.Tasks.Task AddReclamationAsync(Camozzi.Model.DataService.Reclamation t) {
            return base.Channel.AddReclamationAsync(t);
        }
        
        public void DeleteReclamation(Camozzi.Model.DataService.Reclamation t) {
            base.Channel.DeleteReclamation(t);
        }
        
        public System.Threading.Tasks.Task DeleteReclamationAsync(Camozzi.Model.DataService.Reclamation t) {
            return base.Channel.DeleteReclamationAsync(t);
        }
        
        public void UpdateReclamation(Camozzi.Model.DataService.Reclamation t) {
            base.Channel.UpdateReclamation(t);
        }
        
        public System.Threading.Tasks.Task UpdateReclamationAsync(Camozzi.Model.DataService.Reclamation t) {
            return base.Channel.UpdateReclamationAsync(t);
        }
        
        public Camozzi.Model.DataService.Reclamation[] GetByDateReclamation(System.DateTime start, System.DateTime finish) {
            return base.Channel.GetByDateReclamation(start, finish);
        }
        
        public System.Threading.Tasks.Task<Camozzi.Model.DataService.Reclamation[]> GetByDateReclamationAsync(System.DateTime start, System.DateTime finish) {
            return base.Channel.GetByDateReclamationAsync(start, finish);
        }
        
        public void AddUser(Camozzi.Model.DataService.User t) {
            base.Channel.AddUser(t);
        }
        
        public System.Threading.Tasks.Task AddUserAsync(Camozzi.Model.DataService.User t) {
            return base.Channel.AddUserAsync(t);
        }
        
        public void DeleteUser(Camozzi.Model.DataService.User t) {
            base.Channel.DeleteUser(t);
        }
        
        public System.Threading.Tasks.Task DeleteUserAsync(Camozzi.Model.DataService.User t) {
            return base.Channel.DeleteUserAsync(t);
        }
        
        public void UpdateUser(Camozzi.Model.DataService.User t) {
            base.Channel.UpdateUser(t);
        }
        
        public System.Threading.Tasks.Task UpdateUserAsync(Camozzi.Model.DataService.User t) {
            return base.Channel.UpdateUserAsync(t);
        }
        
        public void AddProject(Camozzi.Model.DataService.Project t) {
            base.Channel.AddProject(t);
        }
        
        public System.Threading.Tasks.Task AddProjectAsync(Camozzi.Model.DataService.Project t) {
            return base.Channel.AddProjectAsync(t);
        }
        
        public void DeleteProject(Camozzi.Model.DataService.Project t) {
            base.Channel.DeleteProject(t);
        }
        
        public System.Threading.Tasks.Task DeleteProjectAsync(Camozzi.Model.DataService.Project t) {
            return base.Channel.DeleteProjectAsync(t);
        }
        
        public Camozzi.Model.DataService.User[] GetUsers() {
            return base.Channel.GetUsers();
        }
        
        public System.Threading.Tasks.Task<Camozzi.Model.DataService.User[]> GetUsersAsync() {
            return base.Channel.GetUsersAsync();
        }
        
        public bool CheckPassword(string password, int id) {
            return base.Channel.CheckPassword(password, id);
        }
        
        public System.Threading.Tasks.Task<bool> CheckPasswordAsync(string password, int id) {
            return base.Channel.CheckPasswordAsync(password, id);
        }
        
        public Camozzi.Model.DataService.Reclamation[] GetReclamations() {
            return base.Channel.GetReclamations();
        }
        
        public System.Threading.Tasks.Task<Camozzi.Model.DataService.Reclamation[]> GetReclamationsAsync() {
            return base.Channel.GetReclamationsAsync();
        }
        
        public Camozzi.Model.DataService.Project[] GetByDateAndDeptProject(System.DateTime start, System.DateTime finish, int deptid) {
            return base.Channel.GetByDateAndDeptProject(start, finish, deptid);
        }
        
        public System.Threading.Tasks.Task<Camozzi.Model.DataService.Project[]> GetByDateAndDeptProjectAsync(System.DateTime start, System.DateTime finish, int deptid) {
            return base.Channel.GetByDateAndDeptProjectAsync(start, finish, deptid);
        }
        
        public void UpdateProject(Camozzi.Model.DataService.Project t) {
            base.Channel.UpdateProject(t);
        }
        
        public System.Threading.Tasks.Task UpdateProjectAsync(Camozzi.Model.DataService.Project t) {
            return base.Channel.UpdateProjectAsync(t);
        }
    }
}
