//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Camozzi.Model.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.CreateProjects = new HashSet<Project>();
            this.ManageProjects = new HashSet<Project>();
            this.UserProjects = new HashSet<Project>();
            this.CreateReclamations = new HashSet<Reclamation>();
            this.ManageReclamations = new HashSet<Reclamation>();
            this.UserReclamations = new HashSet<Reclamation>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public int DeptId { get; set; }
        public string Password { get; set; }
        public string Mail { get; set; }
        public int AccountId { get; set; }
        public string Comment { get; set; }
        public object AllProjectsRow { get; set; }
        public object AllReclamationsRow { get; set; }

        public virtual Account Account { get; set; }
        public virtual Dept Dept { get; set; }
        public virtual ICollection<Project> CreateProjects { get; set; }
        public virtual ICollection<Project> ManageProjects { get; set; }
        public virtual ICollection<Project> UserProjects { get; set; }
        public virtual ICollection<Reclamation> CreateReclamations { get; set; }
        public virtual ICollection<Reclamation> ManageReclamations { get; set; }
        public virtual ICollection<Reclamation> UserReclamations { get; set; }

        public override string ToString()
        {
            return Name;
        }
    }
}
